# The directory containing the source files to parse recursively
source: ./aigis/assets

# The directory that aigis will build to
dest: ./docs

# The assets needed to build the docs
# You may put doc related assets here too: images, css, etc.
dependencies:
  - ./aigis/assets

# The directory containing the tempalte files to generate pages
# It must contain 'layout.xxx' and 'index.xxx' (.ejs or .jade or .hbs)
template_dir: ./aigis/template
template_engine: ejs
